# Generated by Django 4.0.4 on 2022-06-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_name', models.CharField(max_length=150)),
                ('slag', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=150)),
                ('slag', models.SlugField(null=True)),
                ('description', models.TextField()),
                ('date_of_birthday', models.DateField()),
                ('experience', models.IntegerField()),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.direction')),
            ],
        ),
    ]
